remove dead code
jlndk/devoops pull request #10
Opened 2020-02-02 17:13 UTC by Hjaltesorgenfrei

Flag tool fix. #4 Man skal blot apt-get install libsqlite3-dev for at kunne build. Kan dog ikke lige finde en god måde at få det automated til at build.

2020-02-02 18:32 UTC, jlndk requested changes
~~Vi burde tilføje nogle "installation/getting started" instrukser i readme så vi kan dokumentere at man har brug for at installere de dependencies manuelt.~~

We should add some "installation/getting started" instructions in the readme, so that we can we can document the requirement of manually installing the dependencies.

2020-02-02 18:49 UTC, Hjaltesorgenfrei reviewed
~~Har fixet det nu~~

Fixed it now

2020-02-02 18:53 UTC, jlndk approved these changes

2020-02-03 10:08 UTC, tobloef commented
Skal makefilen ikke opdateres også? Eller var det ikke nødvendigt?

2020-02-03 14:56 UTC, merged