Pagination
jlndk/devoops pull request #137
Opened 2020-03-26 12:39 UTC by tobloef

Simple pagination for the web app. It's based on dates, since Hjalte wanted that some reason. It's also pretty clean!

2020-04-01 19:28 UTC, tobloef commented
Now includes #133 .

2020-04-01 20:02 UTC, tobloef commented
I think it's good!

2020-04-02 10:38 UTC, Hjaltesorgenfrei requested changes

2020-04-02 10:38 UTC, Hjaltesorgenfrei commented on MiniTwit.Models/MessageRepository.cs
> +            Console.WriteLine($"dateOlderThan: {dateOlderThan}");
If you want to log something, use the log.

2020-04-02 10:55 UTC, Hjaltesorgenfrei approved these changes

2020-04-02 10:55 UTC, merged