2.5 Branching Strategy
jlndk/devoops pull request #200
Opened 2020-05-07 10:41 UTC by tobloef

2020-05-07 10:43 UTC, Duckapple commented
Would it be better to describe GitHub Flow first and then compare and describe afterwards?

2020-05-07 10:45 UTC, tobloef commented
> Would it be better to describe GitHub Flow first and then compare and describe afterwards?

Fixed.

2020-05-07 10:46 UTC, Duckapple approved these changes
looks nice IMO

2020-05-07 11:09 UTC, tobloef commented
Closes #213

2020-05-09 14:20 UTC, Hjaltesorgenfrei requested changes
When and how are we adding References.

2020-05-10 10:59 UTC, Jakobis submitted a review, later dismissed

2020-05-10 10:59 UTC, Jakobis commented on report/25_Process-Branching-Strategy.md
> +Due to the smaller scope and team size, it was decided to use a lightweight, but surprisingly useful, branching strategy called GitHub flow (TODO: ref) (not to be confused with Git flow). GitHub flow
Burde måske få ordnet din todo først?

2020-05-10 10:59 UTC, Jakobis commented on report/25_Process-Branching-Strategy.md
> +Due to the smaller scope and team size, it was decided to use a lightweight, but surprisingly useful, branching strategy called GitHub flow (TODO: ref) (not to be confused with Git flow). GitHub flow
@tobloef

2020-05-10 18:43 UTC, Hjaltesorgenfrei approved these changes

2020-05-10 18:44 UTC, merged