Follows and My Timelines for follows
jlndk/devoops pull request #67
Opened 2020-02-24 00:17 UTC by Hjaltesorgenfrei

Adds the Follow many to many relation, as well as timeline for the people you are following. 
fixes #47, #46, #66

2020-02-24 13:12 UTC, jlndk reviewed
Backend looks sweet, and frontend is okay.
Besides the comments i've added it is worth mentioning that there's quite a bit of code duplication between the views, which could perhaps be cleaned up.
Dunno if this should be resolved now or promoted to a issue

2020-02-24 13:12 UTC, jlndk commented on MiniTwit.Web.App/Views/Home/Index.cshtml
> +        <h3>What's on your mind @* TODO: @ViewData["UserName"] *@?</h3>
Should this todo be fixed, promoted to a issue or something else?

2020-02-24 13:12 UTC, jlndk commented on MiniTwit.Web.App/Views/Home/My_Timeline.cshtml
> +         <h3>What's on your mind @* TODO: @ViewData["UserName"] *@?</h3>
Same about todo

2020-02-24 14:05 UTC, Hjaltesorgenfrei commented
I will fix the code duplication and fix the ToDo, it is quite simple and does not need a issue.

2020-02-24 15:23 UTC, Jakobis requested changes

2020-02-24 15:23 UTC, Jakobis commented on MiniTwit.Models.Test/MessageRepositoryTests.cs
> +                Assert.Equal(1, DateTime.Compare(prev, message.PubDate));
This should not use equal, but just true

2020-02-24 15:23 UTC, Jakobis commented on MiniTwit.Models.Test/MessageRepositoryTests.cs
> +                Assert.Equal(1, DateTime.Compare(prev, message.PubDate));
Same  as above

2020-02-24 15:23 UTC, Jakobis commented on MiniTwit.Models/IMessageRepository.cs
> +        Task<IEnumerable<Message>> ReadAllMessagesFromFollowedAsync(int parse);
Why is parse here?

2020-02-24 15:23 UTC, Jakobis commented on MiniTwit.Models/MessageRepository.cs
> +                orderby m.PubDate descending
Sorry about that

2020-02-25 13:02 UTC, Duckapple approved these changes
Seems good, things work, tests pass, I like

2020-02-25 13:05 UTC, Jakobis approved these changes
Simon told me to just approve without looking

2020-02-25 13:05 UTC, merged